[project]
name = "split-expenses"
version = "1.0.0"
description = "A basic app to split expenses"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipdb>=0.13.13",
    "numpy>=2.3.3",
    "streamlit>=1.50.0",
]
